version: '3.5'
services:
  nest-api-postgres-stage:
    container_name: nest-api-postgres-stage
    image: postgres:12.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - './postgres-volume:/var/lib/postgresql/data'
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
    networks:
      - external-network

  nest-api-redis-stage:
    container_name: nest-api-redis-stage
    image: redis:6.0.8-alpine
    restart: unless-stopped
    command:
      - 'redis-server'
      - '--port ${REDIS_PORT}'
      - '--requirepass ${REDIS_PASSWORD}'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 1'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
    volumes:
      - './redis-volume:/data/redis'
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
    networks:
      - external-network

  nest-api-server:
    container_name: nest-api-server
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        API_PREFIX: ${API_PREFIX}
        HOST: ${HOST}
        PORT: ${PORT}
        EXTERNAL_PORT: ${EXTERNAL_PORT}
        CRYPTO_SECRET: ${CRYPTO_SECRET}
        AUTH_HEADER: ${AUTH_HEADER}
        IDENTITY_HEADER: ${IDENTITY_HEADER}
        JWT_SECRET: ${JWT_SECRET}
        ACCESS_LIFETIME: ${ACCESS_LIFETIME}
        REFRESH_LIFETIME: ${REFRESH_LIFETIME}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_DB: ${REDIS_DB}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_EXTERNAL_PORT: ${REDIS_EXTERNAL_PORT}
        REDIS_TOKEN_PREFIX: ${REDIS_TOKEN_PREFIX}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_EXTERNAL_PORT: ${POSTGRES_EXTERNAL_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DATABASE: ${POSTGRES_DATABASE}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${EXTERNAL_PORT}:${PORT}
    depends_on:
      - nest-api-postgres-stage
      - nest-api-redis-stage
    networks:
      - external-network

networks:
  external-network:
    driver: bridge

