version: '3.5'
services:
  nest-api-postgres-dev:
    container_name: nest-api-postgres-dev
    image: postgres:12.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - './postgres-volume:/var/lib/postgresql/data'
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}

  nest-api-redis-dev:
    container_name: nest-api-redis-dev
    image: redis:6.0.8-alpine
    restart: unless-stopped
    command:
      - 'redis-server'
      - '--port ${REDIS_PORT}'
      - '--requirepass ${REDIS_PASSWORD}'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 1'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
    volumes:
      - './redis-volume:/data/redis'
    ports:
      - ${REDIS_EXTERNAL_PORT}:${REDIS_PORT}
