FROM node:14.15.0 as builder
ARG NODE_ENV
ARG API_PREFIX
ARG HOST
ARG PORT
ARG EXTERNAL_PORT
ARG DB_NAME
ENV NODE_ENV=${NODE_ENV}
ENV API_PREFIX=${API_PREFIX}
ENV HOST=${HOST}
ENV PORT=${PORT}
ENV EXTERNAL_PORT=${EXTERNAL_PORT}
ENV DB_NAME=${DB_NAME}
WORKDIR /usr/app
COPY package*.json ./
RUN npm install --silent
COPY ./ ./
RUN npm run build
RUN npm run migration:run

FROM node:14.15.0-alpine
ARG NODE_ENV
ARG API_PREFIX
ARG HOST
ARG PORT
ARG EXTERNAL_PORT
ARG DB_NAME
ENV NODE_ENV=${NODE_ENV}
ENV API_PREFIX=${API_PREFIX}
ENV HOST=${HOST}
ENV PORT=${PORT}
ENV EXTERNAL_PORT=${EXTERNAL_PORT}
ENV DB_NAME=${DB_NAME}
WORKDIR /usr/app
COPY --from=builder /usr/app/ ./
CMD npm run start:prod